on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
<<<<<<< HEAD
  build_guide:
    runs-on: ubuntu-latest
    name: build_guide
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas.1
          path: ./zmakebas.1
      - uses: actions/checkout@v2
        with:
          repository: chris-y/rman
      - name: build_rman
        id: build_rman
        run: make -f Makefile
      - name: Download zmakebas.1
        uses: actions/download-artifact@v1
        with:
          name: zmakebas.1
      - name: build_guide
        id: build_guide
        run: |
          ls -la
          ./rman -fAmigaGuide ./zmakebas.1 >./zmakebas.guide
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas.guide
          path: ./zmakebas.guide
=======
>>>>>>> parent of e36a71c... Build AmigaGuide documentation
  build_ppc:
    runs-on: ubuntu-latest
    container:
      image: amigadev/crosstools:ppc-amigaos
    name: build_os4
    steps:
      - uses: actions/checkout@v2
      - name: build_os4
        id: build_os4
        run: make -f Makefile zmakebas
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas_os4
          path: zmakebas
  build_68k:
    runs-on: ubuntu-latest
    container:
      image: amigadev/crosstools:m68k-amigaos
    name: build_os3
    steps:
      - uses: actions/checkout@v2
      - name: buildos3
        id: buildos3
        run: make -f Makefile zmakebas
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas_os3
          path: zmakebas
